/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

type ArrayOf<T> = Array<
  T & {
    _key: string
  }
>

// Source: sanity/schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type AboutPage = {
  _id: string
  _type: "aboutPage"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  eyebrow?: string
  headline?: string
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h2" | "h3" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      blank?: boolean
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: "span"
          _key: string
        }>
        style?: "normal" | "h2" | "h3" | "blockquote"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
          href?: string
          blank?: boolean
          _type: "link"
          _key: string
        }>
        level?: number
        _type: "block"
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        caption?: string
        displaySize?: "sm" | "md" | "lg" | "full"
        _type: "image"
        _key: string
      }
    | {
        text?: string
        _type: "quote"
        _key: string
      }
  >
  valuesEyebrow?: string
  valuesHeadline?: string
  values?: Array<
    {
      _key: string
    } & AboutValue
  >
  showSignup?: boolean
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type GetInvolvedPage = {
  _id: string
  _type: "getInvolvedPage"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  eyebrow?: string
  headline?: string
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h2" | "h3" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      blank?: boolean
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  waysEyebrow?: string
  waysHeadline?: string
  ways?: Array<
    {
      _key: string
    } & GetInvolvedWay
  >
  showSignup?: boolean
}

export type ChapterPrioritiesPage = {
  _id: string
  _type: "chapterPrioritiesPage"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  eyebrow?: string
  headline?: string
  intro?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: "span"
          _key: string
        }>
        style?: "normal" | "h2" | "h3" | "blockquote"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
          href?: string
          blank?: boolean
          _type: "link"
          _key: string
        }>
        level?: number
        _type: "block"
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        caption?: string
        displaySize?: "sm" | "md" | "lg" | "full"
        _type: "image"
        _key: string
      }
  >
  priorities?: Array<
    {
      _key: string
    } & Priority
  >
  showSignup?: boolean
}

export type ResourcesPage = {
  _id: string
  _type: "resourcesPage"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  eyebrow?: string
  headline?: string
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h2" | "h3" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      blank?: boolean
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  memberEyebrow?: string
  memberHeadline?: string
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: "span"
          _key: string
        }>
        style?: "normal" | "h2" | "h3" | "blockquote"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
          href?: string
          blank?: boolean
          _type: "link"
          _key: string
        }>
        level?: number
        _type: "block"
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        caption?: string
        displaySize?: "sm" | "md" | "lg" | "full"
        _type: "image"
        _key: string
      }
  >
  communityEyebrow?: string
  communityHeadline?: string
  communityIntro?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h2" | "h3" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      blank?: boolean
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  disclaimerText?: string
  printFooterText?: string
  googleSheetId?: string
  googleSheetRange?: string
  showSignup?: boolean
}

export type WorkingGroups = {
  _id: string
  _type: "workingGroups"
  _createdAt: string
  _updatedAt: string
  _rev: string
  groups?: Array<{
    label?: string
    value?: Slug
    description?: string
    _type: "workingGroupEntry"
    _key: string
  }>
}

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type EventTypes = {
  _id: string
  _type: "eventTypes"
  _createdAt: string
  _updatedAt: string
  _rev: string
  types?: Array<{
    label?: string
    value?: Slug
    color?: string
    description?: string
    _type: "eventTypeEntry"
    _key: string
  }>
}

export type EventsPage = {
  _id: string
  _type: "eventsPage"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  eyebrow?: string
  headline?: string
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h2" | "h3" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      blank?: boolean
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  noFeaturedEventsMessage?: string
  showSignup?: boolean
}

export type Event = {
  _id: string
  _type: "event"
  _createdAt: string
  _updatedAt: string
  _rev: string
  googleEventId?: string
  titleHint?: string
  featured?: boolean
  eventType?: string
  attendance?: "in_person" | "virtual" | "hybrid"
  topics?: Array<string>
  workingGroup?: string
  rsvpLink?: string
  summary?: string
}

export type HomePage = {
  _id: string
  _type: "homePage"
  _createdAt: string
  _updatedAt: string
  _rev: string
  heroHeadline?: string
  heroSubheadline?: string
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  heroCtaText?: string
  heroCtaLink?: string
  heroCta2Text?: string
  heroCta2Link?: string
  heroCtaPosition?: "bottom-left" | "center" | "bottom-right"
  contentEyebrow?: string
  contentHeadline?: string
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: "span"
          _key: string
        }>
        style?: "normal" | "h2" | "h3" | "blockquote"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
          href?: string
          blank?: boolean
          _type: "link"
          _key: string
        }>
        level?: number
        _type: "block"
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        caption?: string
        displaySize?: "sm" | "md" | "lg" | "full"
        _type: "image"
        _key: string
      }
  >
  bodyImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  eventsEyebrow?: string
  eventsHeadline?: string
  eventsImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  noEventsHeadline?: string
  noEventsBody?: string
  noRsvpMessage?: string
}

export type PageReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "page"
}

export type EventsPageReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "eventsPage"
}

export type ChapterPrioritiesPageReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "chapterPrioritiesPage"
}

export type ResourcesPageReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "resourcesPage"
}

export type GetInvolvedPageReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "getInvolvedPage"
}

export type AboutPageReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "aboutPage"
}

export type SiteSettings = {
  _id: string
  _type: "siteSettings"
  _createdAt: string
  _updatedAt: string
  _rev: string
  siteTitle?: string
  siteShortName?: string
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  logoTagline?: string
  mainNav?: ArrayOf<
    | PageReference
    | EventsPageReference
    | ChapterPrioritiesPageReference
    | ResourcesPageReference
    | GetInvolvedPageReference
    | AboutPageReference
  >
  callToActionText?: string
  callToActionLink?: string
  showRibbon?: boolean
  ribbonText?: string
  nextMeetingLabel?: string
  nextMeetingMatch?: string
  nextMeetingTextOverride?: string
  nextMeetingLinkOverride?: string
  bannerWords?: Array<string>
  signupLink?: string
  signupEyebrow?: string
  signupHeadline?: string
  signupDescription?: string
  socialLinks?: Array<{
    platform?: string
    url?: string
    _key: string
  }>
  socialIconStyle?: "outline" | "filled"
  contactEmail?: string
  contactEmailSubject?: string
  footerTagline?: string
  footerNoteLeft?: string
  footerNoteRight?: string
  footerColumns?: Array<{
    title?: string
    links?: Array<{
      label?: string
      href?: string
      _type: "footerLink"
      _key: string
    }>
    _type: "footerColumn"
    _key: string
  }>
}

export type Page = {
  _id: string
  _type: "page"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: "span"
          _key: string
        }>
        style?: "normal" | "h2" | "h3" | "blockquote"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
          href?: string
          blank?: boolean
          _type: "link"
          _key: string
        }>
        level?: number
        _type: "block"
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        caption?: string
        displaySize?: "sm" | "md" | "lg" | "full"
        _type: "image"
        _key: string
      }
  >
}

export type Post = {
  _id: string
  _type: "post"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  mainImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
}

export type AboutValue = {
  _type: "aboutValue"
  headline?: string
  description?: string
}

export type GetInvolvedWay = {
  _type: "getInvolvedWay"
  headline?: string
  description?: string
  ctaText?: string
  ctaLink?: string
}

export type Priority = {
  _type: "priority"
  category?: string
  headline?: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h2" | "h3" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      blank?: boolean
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  ctaText?: string
  ctaLink?: string
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | AboutPage
  | SanityImageCrop
  | SanityImageHotspot
  | GetInvolvedPage
  | ChapterPrioritiesPage
  | ResourcesPage
  | WorkingGroups
  | Slug
  | EventTypes
  | EventsPage
  | Event
  | HomePage
  | PageReference
  | EventsPageReference
  | ChapterPrioritiesPageReference
  | ResourcesPageReference
  | GetInvolvedPageReference
  | AboutPageReference
  | SiteSettings
  | Page
  | Post
  | AboutValue
  | GetInvolvedWay
  | Priority
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: sanity/queries/aboutPage.ts
// Variable: ABOUT_PAGE_QUERY
// Query: {  "page": *[_type == "aboutPage" && _id == "aboutPage"][0] {    _id,    title,    eyebrow,    headline,    intro,    body,    valuesEyebrow,    valuesHeadline,    values[] {      headline,      description    },    showSignup  },}
export type ABOUT_PAGE_QUERY_RESULT = {
  page: {
    _id: "aboutPage"
    title: string | null
    eyebrow: string | null
    headline: string | null
    intro: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "blockquote" | "h2" | "h3" | "normal"
      listItem?: "bullet" | "number"
      markDefs?: Array<{
        href?: string
        blank?: boolean
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }> | null
    body: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: "span"
            _key: string
          }>
          style?: "blockquote" | "h2" | "h3" | "normal"
          listItem?: "bullet" | "number"
          markDefs?: Array<{
            href?: string
            blank?: boolean
            _type: "link"
            _key: string
          }>
          level?: number
          _type: "block"
          _key: string
        }
      | {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          caption?: string
          displaySize?: "full" | "lg" | "md" | "sm"
          _type: "image"
          _key: string
        }
      | {
          text?: string
          _type: "quote"
          _key: string
        }
    > | null
    valuesEyebrow: string | null
    valuesHeadline: string | null
    values: Array<{
      headline: string | null
      description: string | null
    }> | null
    showSignup: boolean | null
  } | null
}

// Source: sanity/queries/chapterPrioritiesPage.ts
// Variable: CHAPTER_PRIORITIES_PAGE_QUERY
// Query: *[_type == "chapterPrioritiesPage" && _id == "chapterPrioritiesPage"][0] {  _id,  title,  eyebrow,  headline,  intro,  priorities[] {    _key,    category,    headline,    description,    image,    ctaText,    ctaLink  }}
export type CHAPTER_PRIORITIES_PAGE_QUERY_RESULT = {
  _id: "chapterPrioritiesPage"
  title: string | null
  eyebrow: string | null
  headline: string | null
  intro: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: "span"
          _key: string
        }>
        style?: "blockquote" | "h2" | "h3" | "normal"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
          href?: string
          blank?: boolean
          _type: "link"
          _key: string
        }>
        level?: number
        _type: "block"
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        caption?: string
        displaySize?: "full" | "lg" | "md" | "sm"
        _type: "image"
        _key: string
      }
  > | null
  priorities: Array<{
    _key: string
    category: string | null
    headline: string | null
    description: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "blockquote" | "h2" | "h3" | "normal"
      listItem?: "bullet" | "number"
      markDefs?: Array<{
        href?: string
        blank?: boolean
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }> | null
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    } | null
    ctaText: string | null
    ctaLink: string | null
  }> | null
} | null

// Source: sanity/queries/eventTypes.ts
// Variable: EVENT_TYPES_QUERY
// Query: *[_type == "eventTypes" && _id == "eventTypes"][0].types[]{    label,    "value": value.current,    color,    description  }
export type EVENT_TYPES_QUERY_RESULT = Array<{
  label: string | null
  value: string | null
  color: string | null
  description: string | null
}> | null

// Source: sanity/queries/events.ts
// Variable: EVENT_CUSTOMIZATIONS_QUERY
// Query: *[_type == "event" && defined(googleEventId)]{    _id,    googleEventId,    featured,    eventType,    attendance,    topics,    workingGroup,    rsvpLink,    summary  }
export type EVENT_CUSTOMIZATIONS_QUERY_RESULT = Array<{
  _id: string
  googleEventId: string
  featured: boolean | null
  eventType: string | null
  attendance: "hybrid" | "in_person" | "virtual" | null
  topics: Array<string> | null
  workingGroup: string | null
  rsvpLink: string | null
  summary: string | null
}>

// Source: sanity/queries/eventsPage.ts
// Variable: EVENTS_PAGE_QUERY
// Query: {  "page": *[_type == "eventsPage" && _id == "eventsPage"][0] {    _id,    title,    eyebrow,    headline,    intro,    noFeaturedEventsMessage,    showSignup  },}
export type EVENTS_PAGE_QUERY_RESULT = {
  page: {
    _id: "eventsPage"
    title: string | null
    eyebrow: string | null
    headline: string | null
    intro: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "blockquote" | "h2" | "h3" | "normal"
      listItem?: "bullet" | "number"
      markDefs?: Array<{
        href?: string
        blank?: boolean
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }> | null
    noFeaturedEventsMessage: string | null
    showSignup: boolean | null
  } | null
}

// Source: sanity/queries/getInvolvedPage.ts
// Variable: GET_INVOLVED_PAGE_QUERY
// Query: {  "page": *[_type == "getInvolvedPage" && _id == "getInvolvedPage"][0] {    _id,    title,    eyebrow,    headline,    intro,    waysEyebrow,    waysHeadline,    ways[] {      headline,      description,      ctaText,      ctaLink    },    showSignup  },}
export type GET_INVOLVED_PAGE_QUERY_RESULT = {
  page: {
    _id: "getInvolvedPage"
    title: string | null
    eyebrow: string | null
    headline: string | null
    intro: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "blockquote" | "h2" | "h3" | "normal"
      listItem?: "bullet" | "number"
      markDefs?: Array<{
        href?: string
        blank?: boolean
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }> | null
    waysEyebrow: string | null
    waysHeadline: string | null
    ways: Array<{
      headline: string | null
      description: string | null
      ctaText: string | null
      ctaLink: string | null
    }> | null
    showSignup: boolean | null
  } | null
}

// Source: sanity/queries/homePage.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage" && _id == "homePage"][0] {    heroHeadline,    heroSubheadline,    heroImage,    heroCtaText,    heroCtaLink,    heroCta2Text,    heroCta2Link,    heroCtaPosition,    contentEyebrow,    contentHeadline,    body,    bodyImage,    eventsEyebrow,    eventsHeadline,    eventsImage,    noEventsHeadline,    noEventsBody,    noRsvpMessage,  }
export type HOME_PAGE_QUERY_RESULT = {
  heroHeadline: string | null
  heroSubheadline: string | null
  heroImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  } | null
  heroCtaText: string | null
  heroCtaLink: string | null
  heroCta2Text: string | null
  heroCta2Link: string | null
  heroCtaPosition: "bottom-left" | "bottom-right" | "center" | null
  contentEyebrow: string | null
  contentHeadline: string | null
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: "span"
          _key: string
        }>
        style?: "blockquote" | "h2" | "h3" | "normal"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
          href?: string
          blank?: boolean
          _type: "link"
          _key: string
        }>
        level?: number
        _type: "block"
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        caption?: string
        displaySize?: "full" | "lg" | "md" | "sm"
        _type: "image"
        _key: string
      }
  > | null
  bodyImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  } | null
  eventsEyebrow: string | null
  eventsHeadline: string | null
  eventsImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  } | null
  noEventsHeadline: string | null
  noEventsBody: string | null
  noRsvpMessage: string | null
} | null

// Source: sanity/queries/page.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: {  "page": *[_type == "page" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    body  },}
export type PAGE_BY_SLUG_QUERY_RESULT = {
  page: {
    _id: string
    title: string | null
    slug: string | null
    body: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: "span"
            _key: string
          }>
          style?: "blockquote" | "h2" | "h3" | "normal"
          listItem?: "bullet" | "number"
          markDefs?: Array<{
            href?: string
            blank?: boolean
            _type: "link"
            _key: string
          }>
          level?: number
          _type: "block"
          _key: string
        }
      | {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          caption?: string
          displaySize?: "full" | "lg" | "md" | "sm"
          _type: "image"
          _key: string
        }
    > | null
  } | null
}

// Source: sanity/queries/resourcesPage.ts
// Variable: RESOURCES_PAGE_QUERY
// Query: {  "page": *[_type == "resourcesPage" && _id == "resourcesPage"][0] {    _id,    title,    eyebrow,    headline,    intro,    memberEyebrow,    memberHeadline,    body,    communityEyebrow,    communityHeadline,    communityIntro,    disclaimerText,    printFooterText,    googleSheetId,    googleSheetRange,    showSignup  },}
export type RESOURCES_PAGE_QUERY_RESULT = {
  page: {
    _id: "resourcesPage"
    title: string | null
    eyebrow: string | null
    headline: string | null
    intro: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "blockquote" | "h2" | "h3" | "normal"
      listItem?: "bullet" | "number"
      markDefs?: Array<{
        href?: string
        blank?: boolean
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }> | null
    memberEyebrow: string | null
    memberHeadline: string | null
    body: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: "span"
            _key: string
          }>
          style?: "blockquote" | "h2" | "h3" | "normal"
          listItem?: "bullet" | "number"
          markDefs?: Array<{
            href?: string
            blank?: boolean
            _type: "link"
            _key: string
          }>
          level?: number
          _type: "block"
          _key: string
        }
      | {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          caption?: string
          displaySize?: "full" | "lg" | "md" | "sm"
          _type: "image"
          _key: string
        }
    > | null
    communityEyebrow: string | null
    communityHeadline: string | null
    communityIntro: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "blockquote" | "h2" | "h3" | "normal"
      listItem?: "bullet" | "number"
      markDefs?: Array<{
        href?: string
        blank?: boolean
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }> | null
    disclaimerText: string | null
    printFooterText: string | null
    googleSheetId: string | null
    googleSheetRange: string | null
    showSignup: boolean | null
  } | null
}

// Source: sanity/queries/siteSettings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {  siteTitle,  siteShortName,  logo,  logoTagline,  "navLinks": mainNav[]{    _key,    "title": @->title,    "slug": select(      @->_type == "eventsPage" => "events",      @->_type == "chapterPrioritiesPage" => "chapter-priorities",      @->_type == "resourcesPage" => "resources",      @->_type == "getInvolvedPage" => "get-involved",      @->_type == "aboutPage" => "about",      @->slug.current    )  },  callToActionText,  callToActionLink,  showRibbon,  ribbonText,  nextMeetingLabel,  nextMeetingMatch,  nextMeetingTextOverride,  nextMeetingLinkOverride,  bannerWords,  signupLink,  signupEyebrow,  signupHeadline,  signupDescription,  socialLinks,  socialIconStyle,  contactEmail,  contactEmailSubject,  footerTagline,  footerNoteLeft,  footerNoteRight,  footerColumns[]{    _key,    title,    links[]{ _key, label, href }  }}
export type SITE_SETTINGS_QUERY_RESULT = {
  siteTitle: string | null
  siteShortName: string | null
  logo: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  } | null
  logoTagline: string | null
  navLinks: Array<
    | {
        _key: null
        title: string | null
        slug: "about"
      }
    | {
        _key: null
        title: string | null
        slug: "chapter-priorities"
      }
    | {
        _key: null
        title: string | null
        slug: "events"
      }
    | {
        _key: null
        title: string | null
        slug: "get-involved"
      }
    | {
        _key: null
        title: string | null
        slug: "resources"
      }
    | {
        _key: null
        title: string | null
        slug: string | null
      }
  > | null
  callToActionText: string | null
  callToActionLink: string | null
  showRibbon: boolean | null
  ribbonText: string | null
  nextMeetingLabel: string | null
  nextMeetingMatch: string | null
  nextMeetingTextOverride: string | null
  nextMeetingLinkOverride: string | null
  bannerWords: Array<string> | null
  signupLink: string | null
  signupEyebrow: string | null
  signupHeadline: string | null
  signupDescription: string | null
  socialLinks: Array<{
    platform?: string
    url?: string
    _key: string
  }> | null
  socialIconStyle: "filled" | "outline" | null
  contactEmail: string | null
  contactEmailSubject: string | null
  footerTagline: string | null
  footerNoteLeft: string | null
  footerNoteRight: string | null
  footerColumns: Array<{
    _key: string
    title: string | null
    links: Array<{
      _key: string
      label: string | null
      href: string | null
    }> | null
  }> | null
} | null

// Source: sanity/queries/workingGroups.ts
// Variable: WORKING_GROUPS_QUERY
// Query: *[_type == "workingGroups" && _id == "workingGroups"][0].groups[]{    label,    "value": value.current,    description  }
export type WORKING_GROUPS_QUERY_RESULT = Array<{
  label: string | null
  value: string | null
  description: string | null
}> | null

// Query TypeMap
import "@sanity/client"
declare module "@sanity/client" {
  interface SanityQueries {
    '{\n  "page": *[_type == "aboutPage" && _id == "aboutPage"][0] {\n    _id,\n    title,\n    eyebrow,\n    headline,\n    intro,\n    body,\n    valuesEyebrow,\n    valuesHeadline,\n    values[] {\n      headline,\n      description\n    },\n    showSignup\n  },\n}': ABOUT_PAGE_QUERY_RESULT
    '*[_type == "chapterPrioritiesPage" && _id == "chapterPrioritiesPage"][0] {\n  _id,\n  title,\n  eyebrow,\n  headline,\n  intro,\n  priorities[] {\n    _key,\n    category,\n    headline,\n    description,\n    image,\n    ctaText,\n    ctaLink\n  }\n}': CHAPTER_PRIORITIES_PAGE_QUERY_RESULT
    '\n  *[_type == "eventTypes" && _id == "eventTypes"][0].types[]{\n    label,\n    "value": value.current,\n    color,\n    description\n  }\n': EVENT_TYPES_QUERY_RESULT
    '\n  *[_type == "event" && defined(googleEventId)]{\n    _id,\n    googleEventId,\n    featured,\n    eventType,\n    attendance,\n    topics,\n    workingGroup,\n    rsvpLink,\n    summary\n  }\n': EVENT_CUSTOMIZATIONS_QUERY_RESULT
    '{\n  "page": *[_type == "eventsPage" && _id == "eventsPage"][0] {\n    _id,\n    title,\n    eyebrow,\n    headline,\n    intro,\n    noFeaturedEventsMessage,\n    showSignup\n  },\n}': EVENTS_PAGE_QUERY_RESULT
    '{\n  "page": *[_type == "getInvolvedPage" && _id == "getInvolvedPage"][0] {\n    _id,\n    title,\n    eyebrow,\n    headline,\n    intro,\n    waysEyebrow,\n    waysHeadline,\n    ways[] {\n      headline,\n      description,\n      ctaText,\n      ctaLink\n    },\n    showSignup\n  },\n}': GET_INVOLVED_PAGE_QUERY_RESULT
    '\n  *[_type == "homePage" && _id == "homePage"][0] {\n    heroHeadline,\n    heroSubheadline,\n    heroImage,\n    heroCtaText,\n    heroCtaLink,\n    heroCta2Text,\n    heroCta2Link,\n    heroCtaPosition,\n    contentEyebrow,\n    contentHeadline,\n    body,\n    bodyImage,\n    eventsEyebrow,\n    eventsHeadline,\n    eventsImage,\n    noEventsHeadline,\n    noEventsBody,\n    noRsvpMessage,\n  }\n': HOME_PAGE_QUERY_RESULT
    '{\n  "page": *[_type == "page" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    body\n  },\n}': PAGE_BY_SLUG_QUERY_RESULT
    '{\n  "page": *[_type == "resourcesPage" && _id == "resourcesPage"][0] {\n    _id,\n    title,\n    eyebrow,\n    headline,\n    intro,\n    memberEyebrow,\n    memberHeadline,\n    body,\n    communityEyebrow,\n    communityHeadline,\n    communityIntro,\n    disclaimerText,\n    printFooterText,\n    googleSheetId,\n    googleSheetRange,\n    showSignup\n  },\n}': RESOURCES_PAGE_QUERY_RESULT
    '*[_type == "siteSettings"][0] {\n  siteTitle,\n  siteShortName,\n  logo,\n  logoTagline,\n  "navLinks": mainNav[]{\n    _key,\n    "title": @->title,\n    "slug": select(\n      @->_type == "eventsPage" => "events",\n      @->_type == "chapterPrioritiesPage" => "chapter-priorities",\n      @->_type == "resourcesPage" => "resources",\n      @->_type == "getInvolvedPage" => "get-involved",\n      @->_type == "aboutPage" => "about",\n      @->slug.current\n    )\n  },\n  callToActionText,\n  callToActionLink,\n  showRibbon,\n  ribbonText,\n  nextMeetingLabel,\n  nextMeetingMatch,\n  nextMeetingTextOverride,\n  nextMeetingLinkOverride,\n  bannerWords,\n  signupLink,\n  signupEyebrow,\n  signupHeadline,\n  signupDescription,\n  socialLinks,\n  socialIconStyle,\n  contactEmail,\n  contactEmailSubject,\n  footerTagline,\n  footerNoteLeft,\n  footerNoteRight,\n  footerColumns[]{\n    _key,\n    title,\n    links[]{ _key, label, href }\n  }\n}': SITE_SETTINGS_QUERY_RESULT
    '\n  *[_type == "workingGroups" && _id == "workingGroups"][0].groups[]{\n    label,\n    "value": value.current,\n    description\n  }\n': WORKING_GROUPS_QUERY_RESULT
  }
}
