/**
 * Reads the routes out of src/pages so the Studio can tell an internal path
 * from a typo without anyone maintaining a second copy of the route list.
 *
 * Writes sanity/generated/routes.ts. Runs as part of `npm run typegen`, and the
 * pre-commit hook fails if the committed output is stale.
 */
import { readdir, writeFile } from "node:fs/promises"
import { dirname, join, relative, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { format, resolveConfig } from "prettier"

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const pagesDir = join(appRoot, "src/pages")
const outFile = join(appRoot, "sanity/generated/routes.ts")

/** Astro treats these as pages; everything else under src/pages is an endpoint. */
const PAGE_EXTENSIONS = [".astro", ".md", ".mdx", ".html"]

const collectPageFiles = async (dir) => {
  const entries = await readdir(dir, { withFileTypes: true })

  const found = await Promise.all(
    entries.map(async (entry) => {
      // Astro skips anything prefixed with _, and api/ holds endpoints, not pages.
      if (entry.name.startsWith("_")) return []

      const path = join(dir, entry.name)
      if (entry.isDirectory()) return collectPageFiles(path)

      const isPage = PAGE_EXTENSIONS.some((ext) => entry.name.endsWith(ext))
      return isPage ? [path] : []
    })
  )

  return found.flat()
}

/** src/pages/about.astro -> /about, src/pages/index.astro -> / */
const toRoute = (file) => {
  const withoutExtension = relative(pagesDir, file).replace(/\.[^.]+$/, "")
  const segments = withoutExtension.split("/").filter((s) => s !== "index")
  return `/${segments.join("/")}`.replace(/\/$/, "") || "/"
}

const isDynamic = (route) => route.includes("[")

const serialize = (name, comment, routes) =>
  [
    comment,
    `export const ${name}: readonly string[] = [`,
    ...routes.map((route) => `  ${JSON.stringify(route)},`),
    `]`,
  ].join("\n")

const files = await collectPageFiles(pagesDir)
const routes = files.map(toRoute).sort()

const contents = `${[
  "// Generated by scripts/generate-routes.mjs. Do not edit by hand.",
  "// Run `npm run typegen` after adding or renaming a page.",
  "",
  serialize(
    "STATIC_ROUTES",
    "/** Every page with a fixed path. */",
    routes.filter((route) => !isDynamic(route))
  ),
  "",
  serialize(
    "DYNAMIC_ROUTES",
    [
      "/**",
      " * Pages with a `[param]` segment. What fills that segment lives in the CMS,",
      " * so matching a pattern here only means a path *could* resolve.",
      " */",
    ].join("\n"),
    routes.filter(isDynamic)
  ),
].join("\n")}\n`

// Formatted here so the committed file matches what `format:check` expects.
const prettierOptions = await resolveConfig(outFile)
const formatted = await format(contents, {
  ...prettierOptions,
  parser: "typescript",
})

await writeFile(outFile, formatted, "utf8")
console.log(`Wrote ${relative(appRoot, outFile)} (${routes.length} routes)`)
